Repository jenkins-infra/ircbot, pull requests merged in 2019-11, with the labels that each got.

#68 Fix links and guidelines in the Documentation for IRC Bot
  README.md
Labels: documentation

#70 Fix the ci.jenkins.io badge
  README.md
Labels: documentation

#67 [WEBSITE-672] - Refresh the HOSTING automated message to reflect the plugin documentation pages
  src/main/java/org/jenkinsci/backend/ircbot/IrcListener.java
Labels: enhancement

#69 Create a Release Drafter configuration for IRC Bot
  .github/release-drafter.yml
Labels: chore
